version: '3.3'

services:
    db:
        image: arm64v8/postgres:12.3-alpine
        container_name: postgres-null
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
            - ./data:/var/lib/postgresql/data
        logging:
            driver: "json-file"
            options:
                max-size: "100m"
                max-file: "10"
