# Use postgres/example user/password credentials
version: '3.3'

services:
    elasticsearch:
        image: elasticsearch:6.8.23
        container_name: elasticsearch
        ports:
            - 9200:9200
        environment:
            - discovery.type=single-node
            - action.auto_create_index=true
        volumes:
            - ./data:/data/elk'
        restart: unless-stopped

    kibana:
        image: kibana:6.8.23
        container_name: kibana
        ports:
        - '5601:5601'
        volumes:
        - './data:/data/kibana'
        restart: always
        depends_on:
        - elasticsearch
